// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BackgroundOperationPhase } from "./BackgroundOperationPhase";

export type BackgroundOperationProgressEvent = { operationId: string, instanceId: string, phase: BackgroundOperationPhase, message: string, step: number, total: number, currentItem: string | null, };
