// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GithubAssetResponse = { url: string, id: number, node_id: string, name: string, label: string | null, content_type: string, state: string, size: number, download_count: number, created_at: string, updated_at: string, browser_download_url: string, };
