// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GithubAssetResponse } from "./GithubAssetResponse";

export type GithubReleaseResponse = { url: string, assets_url: string, upload_url: string, html_url: string, id: number, node_id: string, tag_name: string, target_commitish: string, name: string, draft: boolean, prerelease: boolean, created_at: string, published_at: string, assets: Array<GithubAssetResponse>, tarball_url: string, zipball_url: string, body: string, };
