// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GithubAssetResponse } from "./GithubAssetResponse";

export type GithubReleaseResponse = {
  url: string;
  assetsUrl: string;
  uploadUrl: string;
  htmlUrl: string;
  id: number;
  nodeId: string;
  tagName: string;
  targetCommitish: string;
  name: string;
  draft: boolean;
  prerelease: boolean;
  createdAt: string;
  publishedAt: string;
  assets: Array<GithubAssetResponse>;
  tarballUrl: string;
  zipballUrl: string;
  body: string;
};
