// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GithubAssetResponse = {
  url: string;
  id: number;
  nodeId: string;
  name: string;
  label: string | null;
  contentType: string;
  state: string;
  size: number;
  downloadCount: number;
  createdAt: string;
  updatedAt: string;
  browserDownloadUrl: string;
};
