// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type InstanceConnectionSettings = { name: string, description: string, host: string, port: number, password: string, isSynced: boolean, syncPort?: number | null, };
