// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ManifestFileEntry } from "./ManifestFileEntry";
import type { PackageKind } from "./PackageKind";
import type { PluginEntry } from "./PluginEntry";

export type ManifestPackage = { id: string, name: string, kind: PackageKind, relativeDir: string, priority: number, treeChecksum: string, totalSizeBytes: number, fileCount: number, files: Array<ManifestFileEntry>, plugins: Array<PluginEntry>, };
