// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ManifestValidationIssue } from "./ManifestValidationIssue";

export type ManifestValidationResult = { valid: boolean, issues: Array<ManifestValidationIssue>, };
