// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InstanceConfig } from "./InstanceConfig";

export type NerevarConfig = { onboardingComplete: boolean, ownedInstances: Array<InstanceConfig> | null, syncedInstances: Array<InstanceConfig> | null, rootPath: string | null, syncPort: number, };
