// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InstanceConfig } from "./InstanceConfig";

export type NerevarConfig = {
  onboardingComplete: boolean;
  instances: Array<InstanceConfig> | null;
  rootInstancePath: string | null;
  baseTes3mpPath: string | null;
  syncPort: number;
};
