// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SyncHostStatus = { syncPort: number, serverOnline: boolean, hostingInstanceId: string | null, hostingInstanceName: string | null, manifestAvailable: boolean, };
