// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Tes3mpGameSettingEntry } from "./Tes3mpGameSettingEntry";
import type { SettingValue } from "./SettingValue";

export type InstanceSettings = {
  version: number;
  tes3mpGameSettings: Array<Tes3mpGameSettingEntry>;
  openmwSettings: Record<string, Record<string, SettingValue>>;
};
