// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ResolvedOpenMwConfig = { encoding: string, dataPaths: Array<string>, content: Array<string>, };
